export interface LogoTypeInterface {
  Bug: string,
  Dragon: string,
  Electric: string,
  Fairy: string,
  Fighting: string,
  Fire: string,
  Flying: string,
  Ghost: string,
  Grass: string,
  Ground: string,
  Ice: string,
  Normal: string,
  Poison: string,
  Psychic: string,
  Rock: string,
  Steel: string,
  Water: string,
};